name: Deploy Frontend to S3

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: me-central-1 # change if needed
      S3_BUCKET: wetarseel-fe # <-- CHANGE THIS
      CLOUDFRONT_DISTRIBUTION_ID: E2OE9DGUYFVQEQ # <-- optional, for invalidation

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build frontend
        working-directory: apps/web
        run: bun run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync apps/web/dist s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache (optional)
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
